### ISSUE TITLE
Tags? Is this jsr181/jsr181-api or javax.jws

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jws-api#1]
I need this as a dependency of [spring-web](https://github.com/spring-projects/spring-framework/blob/master/spring-web/spring-web.gradle#L32) I cannot tell if this is [jsr181/jsr181-api](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22javax.jws%22) or [javax.jws](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22javax.jws%22).

I see a 1.1 snapshot, so that would match versioning of jsr181. I do not see the [javax.jws-api artifact id per the pom.xml](https://github.com/javaee/javax.jws/blob/master/pom.xml#L53) in [maven central repo](http://search.maven.org/#search%7Cga%7C1%7Cjavax.jws-api).

I can grab a snapshot tag for my needs, but just curious in general if this is the proper home. If tags can be added, etc. thanks!

**Comment by dblevins** [comment]
@Tomas-Kraus I believe you are correct.  This is JSR 109, not 181.

**Comment by dblevins** [comment]
Coming back to contradict myself.  It appears as though `javax.jws` is delivered out of 181, not 109.

**Comment by wltjr** [comment]
I am good per the original issue. There is a 1.1.1 tag/release, and a new 2.1.0. I believe that resolves the initial issue from javaee repo. Thanks!

**Comment by lukasj** [comment]
Jsr181-api.jar is just the wrong name of javax.jws-api.jar, nothing else. #42 did set the appropriate version to the jar.

**Comment by lukasj** [comment]
current (and correct) artifact now from this repo is going to be jakarta.jws:jakarta.jws-api:2.1.0
