### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jws-api#4]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by Tomas-Kraus** [comment]
Added https://jenkins.eclipse.org/jaxws/job/jws-api-master-build/

**Comment by Tomas-Kraus** [comment]
Added https://jenkins.eclipse.org/jaxws/job/jws-api-ee4j8-build/ for EE4J_8 branch

**Comment by Tomas-Kraus** [comment]
Both jobs are working fine, closing this issue.
