### ISSUE TITLE
Please verify that spec api artifacts for 2.1.0 are available on maven central...

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jws-api#48]
Is the Jenkins job that handled the 2.1.0 spec api release pushing to Maven central?  

[Maven repo only seems to have 1.1.1](https://mvnrepository.com/artifact/jakarta.jws/jakarta.jws-api)

CC @lukasj + @Tomas-Kraus

**Comment by lukasj** [comment]
there's no 2.1.0 right now. It must go through ballot first.

**Comment by dufoli** [comment]
same issue here ;-) will it be releasd soon ?

**Comment by lukasj** [comment]
this is done
