### ISSUE TITLE
Merge (original) Web Services Metadata specification source

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jws-api#57]
Just an FYI...  The original (oracle) Web Services Metadata specification source is now available via this CQ:  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21464

Please import/modify/merge it when time allows, hopefully in time for Jakarta EE 9.  Thanks!

**Comment by kwsutter** [comment]
Part of the work outlined by the Jakarta EE 9 Issue #52.

**Comment by lukasj** [comment]
fixed by #59
