### ISSUE TITLE
Change name of xsd file

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jws-api#61]
On the Platform call today, it was pointed out that the XSD for JWS-API still had the "javaee" name.  This needs to change to use the "jakartaee" name...  Just creating this Issue so that we don't forget...

https://github.com/eclipse-ee4j/jws-api/blob/master/api/src/main/resources/jakarta/jws/javaee_web_services_metadata_handler_2_0.xsd

-->

https://github.com/eclipse-ee4j/jws-api/blob/master/api/src/main/resources/jakarta/jws/jakartaee_web_services_metadata_handler_2_0.xsd

**Comment by lukasj** [comment]
fixed in #62 , note that version changed to 3.0 to follow spec version
