### ISSUE TITLE
Update EFSL for Specifications and Javadoc

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jws-api#68]
Per the discussions on the Spec Committee and Platform Dev mailing lists, it's been discovered that many of the Javadoc and Spec references to the EFSL need updating. Please reference the following required updates and keep them in mind as your Spec Project is updating the files for Jakarta EE 9.

Note: Some Spec Projects have already started or even completed these updates. If so, just kindly return/close this Issue. Thanks!

**Required EFSL updates for Javadoc**

For javadoc, the EFSL.html located in src/main/javadoc/doc-files should be modified as follows:
* the `<<url to this license>>` needs to be replaced with efsl.php link[1]
* the `[title and URI of the Eclipse Foundation specification document]` needs to be replaced with the Specification Name and URL (Reference [2] for an example.)
* The javadoc footer copyright year needs to be updated to 2018, 2020 as defined in the pom.xml

**Required EFSL updates for Specifications**

For specification, the license-efsl.adoc located in src/main/asciidoc should be modified as follows:
* Update copyright year to 2018, 2020 from 2019. Add link to EFSL.
* the `<<url to this license>>` needs to be replaced with efsl.php link[1]
* the `[title and URI of the Eclipse Foundation specification document]` needs to be replaced with the Specification Name and URL (Reference [2] for an example.)

[1] https://www.eclipse.org/legal/efsl.php  
[2] https://jakarta.ee/specifications/enterprise-beans/4.0/

**Comment by lukasj** [comment]
is this the issue not supposed to be created based on https://www.eclipse.org/lists/jakartaee-platform-dev/msg01775.html ? In the other words, is just closing this the right way for resolution or do we have to actually do  something more?

**Comment by lukasj** [comment]
@kwsutter ^^^

**Comment by kwsutter** [comment]
@lukasj It's not that the issues were not supposed to be created.  It's just that the wording in the description may be stronger than required.  I decided to leave these issues in place and let each component determine whether changes are necessary or not.  I am not doing any verification if the requested changes were performed or not.  It's up to the component to decide what's appropriate.  Thanks!

**Comment by lukasj** [comment]
ok, thanks. I believe nothing needs to be done then.
